services:
    nuxt:
        build:
            context: .
            dockerfile: .docker/nuxt/Dockerfile
        ports:
            - 3030:3000
        env_file:
            - .env
        volumes:
            - ./:/code
        networks:
            ecas:

networks:
    ecas:
