export default defineEventHandler(async (event) => {
    const mockProducts = [
        {
            _id: 'prod-1',
            erpItemId: 'ERP-001',
            path: 'electronics/smartphone',
            category: 'Electronics',
            active: true,
            class: 'Premium',
            name: 'SmartPhone Pro Max',
            alias: 'smartphone-pro-max',
            description: 'Latest flagship smartphone with cutting-edge features and premium build quality.',
            code: 'SPM-001',
            manufacturer: 'TechBrand Inc.',
            manufacturerCode: 'TBI',
            stock: 150,
            sold: 1250,
            favourite: false,
            priceHistory: [
                { price: 899.99, active: true, createdAt: '2024-01-01T00:00:00.000Z' },
                { price: 849.99, active: false, createdAt: '2024-02-01T00:00:00.000Z' },
            ],
            priceConfiguration: {
                smartLinkId: 'smart-price-1',
                configuration: [
                    { price: 899.99, quantity: 1, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 879.99, quantity: 5, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 859.99, quantity: 10, createdAt: '2024-01-15T00:00:00.000Z' },
                ],
            },
            measure: 'Unit',
            details: {
                SummaryData: {
                    Datasheet: 'datasheet-spm-001.pdf',
                    TaxonomyPath: 'Electronics > Smartphones > Flagship',
                    TaxonomyPathIDs: 'cat-001,cat-012,cat-045',
                    SmallImageURL: 'https://example.com/images/smartphone-pro-small.jpg',
                    PartDescription: '5G LTE, 128GB storage, 6.7" display',
                    Manufacturer: 'TechBrand Inc.',
                },
                ParametricData: {
                    Features: [
                        { FeatureName: 'Display Size', FeatureValue: '6.7"', FeatureUnit: 'inches', FeatureID: 'feat-001' },
                        { FeatureName: 'Storage', FeatureValue: '128GB', FeatureUnit: 'GB', FeatureID: 'feat-002' },
                        { FeatureName: 'RAM', FeatureValue: '8GB', FeatureUnit: 'GB', FeatureID: 'feat-003' },
                        { FeatureName: 'Camera', FeatureValue: '108MP', FeatureUnit: 'MP', FeatureID: 'feat-004' },
                        { FeatureName: 'Battery', FeatureValue: '4500mAh', FeatureUnit: 'mAh', FeatureID: 'feat-005' },
                    ],
                },
                ProductImage: {
                    ProductImageSmall: 'https://example.com/images/smartphone-pro-small.jpg',
                    ProductImageLarge: 'https://example.com/images/smartphone-pro-large.jpg',
                },
            },
        },
        {
            _id: 'prod-2',
            erpItemId: 'ERP-002',
            path: 'electronics/laptop',
            category: 'Electronics',
            active: true,
            class: 'Business',
            name: 'Professional Laptop Ultra',
            alias: 'laptop-ultra-pro',
            description: 'High-performance laptop designed for professionals and creative work.',
            code: 'LAP-002',
            manufacturer: 'TechSystems LLC',
            manufacturerCode: 'TSL',
            stock: 75,
            sold: 890,
            favourite: true,
            priceHistory: [
                { price: 1299.99, active: true, createdAt: '2024-01-01T00:00:00.000Z' },
                { price: 1249.99, active: false, createdAt: '2024-02-01T00:00:00.000Z' },
            ],
            priceConfiguration: {
                smartLinkId: 'smart-price-2',
                configuration: [
                    { price: 1299.99, quantity: 1, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 1274.99, quantity: 5, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 1249.99, quantity: 10, createdAt: '2024-01-15T00:00:00.000Z' },
                ],
            },
            measure: 'Unit',
            details: {
                SummaryData: {
                    Datasheet: 'datasheet-lap-002.pdf',
                    TaxonomyPath: 'Electronics > Laptops > Business',
                    TaxonomyPathIDs: 'cat-001,cat-020,cat-055',
                    SmallImageURL: 'https://example.com/images/laptop-ultra-small.jpg',
                    PartDescription: 'Intel i7, 16GB RAM, 512GB SSD, 15.6" display',
                    Manufacturer: 'TechSystems LLC',
                },
                ParametricData: {
                    Features: [
                        { FeatureName: 'Processor', FeatureValue: 'Intel i7-12700H', FeatureUnit: 'CPU', FeatureID: 'feat-010' },
                        { FeatureName: 'RAM', FeatureValue: '16GB', FeatureUnit: 'GB', FeatureID: 'feat-011' },
                        { FeatureName: 'Storage', FeatureValue: '512GB', FeatureUnit: 'GB', FeatureID: 'feat-012' },
                        { FeatureName: 'Display', FeatureValue: '15.6"', FeatureUnit: 'inches', FeatureID: 'feat-013' },
                        { FeatureName: 'Graphics', FeatureValue: 'RTX 3060', FeatureUnit: '', FeatureID: 'feat-014' },
                    ],
                },
                ProductImage: {
                    ProductImageSmall: 'https://example.com/images/laptop-ultra-small.jpg',
                    ProductImageLarge: 'https://example.com/images/laptop-ultra-large.jpg',
                },
            },
        },
        {
            _id: 'prod-3',
            erpItemId: 'ERP-003',
            path: 'components/keyboard',
            category: 'Components',
            active: true,
            class: 'Standard',
            name: 'Mechanical Keyboard RGB',
            alias: 'keyboard-mech-rgb',
            description: 'Premium mechanical keyboard with customizable RGB backlighting.',
            code: 'KEY-003',
            manufacturer: 'InputDevices Corp',
            manufacturerCode: 'IDC',
            stock: 500,
            sold: 2340,
            favourite: false,
            priceHistory: [
                { price: 89.99, active: true, createdAt: '2024-01-01T00:00:00.000Z' },
                { price: 79.99, active: false, createdAt: '2024-02-01T00:00:00.000Z' },
            ],
            priceConfiguration: {
                smartLinkId: 'smart-price-3',
                configuration: [
                    { price: 89.99, quantity: 1, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 84.99, quantity: 10, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 79.99, quantity: 25, createdAt: '2024-01-15T00:00:00.000Z' },
                ],
            },
            measure: 'Unit',
            details: {
                SummaryData: {
                    Datasheet: 'datasheet-key-003.pdf',
                    TaxonomyPath: 'Components > Keyboards > Mechanical',
                    TaxonomyPathIDs: 'cat-030,cat-075,cat-102',
                    SmallImageURL: 'https://example.com/images/keyboard-mech-small.jpg',
                    PartDescription: 'Cherry MX Brown, RGB backlight, USB-C',
                    Manufacturer: 'InputDevices Corp',
                },
                ParametricData: {
                    Features: [
                        { FeatureName: 'Switch Type', FeatureValue: 'Cherry MX Brown', FeatureUnit: '', FeatureID: 'feat-020' },
                        { FeatureName: 'Backlight', FeatureValue: 'RGB', FeatureUnit: '', FeatureID: 'feat-021' },
                        { FeatureName: 'Connection', FeatureValue: 'USB-C', FeatureUnit: '', FeatureID: 'feat-022' },
                        { FeatureName: 'Keys', FeatureValue: '104', FeatureUnit: 'count', FeatureID: 'feat-023' },
                    ],
                },
                ProductImage: {
                    ProductImageSmall: 'https://example.com/images/keyboard-mech-small.jpg',
                    ProductImageLarge: 'https://example.com/images/keyboard-mech-large.jpg',
                },
            },
        },
        {
            _id: 'prod-4',
            erpItemId: 'ERP-004',
            path: 'audio/headphones',
            category: 'Audio',
            active: true,
            class: 'Premium',
            name: 'Wireless Noise-Canceling Headphones',
            alias: 'headphones-nc-wireless',
            description: 'High-quality wireless headphones with active noise cancellation.',
            code: 'AUD-004',
            manufacturer: 'SoundMaster Inc',
            manufacturerCode: 'SMI',
            stock: 200,
            sold: 1560,
            favourite: false,
            priceHistory: [
                { price: 249.99, active: true, createdAt: '2024-01-01T00:00:00.000Z' },
                { price: 229.99, active: false, createdAt: '2024-02-01T00:00:00.000Z' },
            ],
            priceConfiguration: {
                smartLinkId: 'smart-price-4',
                configuration: [
                    { price: 249.99, quantity: 1, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 239.99, quantity: 5, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 229.99, quantity: 10, createdAt: '2024-01-15T00:00:00.000Z' },
                ],
            },
            measure: 'Unit',
            details: {
                SummaryData: {
                    Datasheet: 'datasheet-aud-004.pdf',
                    TaxonomyPath: 'Audio > Headphones > Wireless',
                    TaxonomyPathIDs: 'cat-040,cat-080,cat-115',
                    SmallImageURL: 'https://example.com/images/headphones-wireless-small.jpg',
                    PartDescription: 'ANC 30h battery, Bluetooth 5.0, 40mm drivers',
                    Manufacturer: 'SoundMaster Inc',
                },
                ParametricData: {
                    Features: [
                        { FeatureName: 'Driver Size', FeatureValue: '40mm', FeatureUnit: 'mm', FeatureID: 'feat-030' },
                        { FeatureName: 'Battery Life', FeatureValue: '30 hours', FeatureUnit: 'hours', FeatureID: 'feat-031' },
                        { FeatureName: 'Bluetooth', FeatureValue: '5.0', FeatureUnit: 'version', FeatureID: 'feat-032' },
                        { FeatureName: 'ANC', FeatureValue: 'Yes', FeatureUnit: '', FeatureID: 'feat-033' },
                    ],
                },
                ProductImage: {
                    ProductImageSmall: 'https://example.com/images/headphones-wireless-small.jpg',
                    ProductImageLarge: 'https://example.com/images/headphones-wireless-large.jpg',
                },
            },
        },
        {
            _id: 'prod-5',
            erpItemId: 'ERP-005',
            path: 'accessories/cable',
            category: 'Accessories',
            active: true,
            class: 'Standard',
            name: 'USB-C Cable 2m',
            alias: 'cable-usb-c-2m',
            description: 'High-speed USB-C cable with nylon braiding.',
            code: 'CBL-005',
            manufacturer: 'CablePro',
            manufacturerCode: 'CBL',
            stock: 1000,
            sold: 5670,
            favourite: false,
            priceHistory: [
                { price: 12.99, active: true, createdAt: '2024-01-01T00:00:00.000Z' },
                { price: 11.99, active: false, createdAt: '2024-02-01T00:00:00.000Z' },
            ],
            priceConfiguration: {
                smartLinkId: 'smart-price-5',
                configuration: [
                    { price: 12.99, quantity: 1, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 11.99, quantity: 50, createdAt: '2024-01-15T00:00:00.000Z' },
                    { price: 10.99, quantity: 100, createdAt: '2024-01-15T00:00:00.000Z' },
                ],
            },
            measure: 'Unit',
            details: {
                SummaryData: {
                    Datasheet: 'datasheet-cbl-005.pdf',
                    TaxonomyPath: 'Accessories > Cables > USB',
                    TaxonomyPathIDs: 'cat-050,cat-090,cat-130',
                    SmallImageURL: 'https://example.com/images/cable-usb-c-small.jpg',
                    PartDescription: 'USB-C 3.1, 480Mbps, nylon braiding',
                    Manufacturer: 'CablePro',
                },
                ParametricData: {
                    Features: [
                        { FeatureName: 'Length', FeatureValue: '2m', FeatureUnit: 'meters', FeatureID: 'feat-040' },
                        { FeatureName: 'Connector', FeatureValue: 'USB-C', FeatureUnit: '', FeatureID: 'feat-041' },
                        { FeatureName: 'Speed', FeatureValue: '480Mbps', FeatureUnit: 'Mbps', FeatureID: 'feat-042' },
                        { FeatureName: 'Material', FeatureValue: 'Nylon', FeatureUnit: '', FeatureID: 'feat-043' },
                    ],
                },
                ProductImage: {
                    ProductImageSmall: 'https://example.com/images/cable-usb-c-small.jpg',
                    ProductImageLarge: 'https://example.com/images/cable-usb-c-large.jpg',
                },
            },
        },
    ];

    return {
        status: 'success',
        data: mockProducts,
    };
});
